const nome = 'FRANCISCA SILVANIR ALVES DOS SANTOS,'
const escola = 'EEIF. JOAQUIM SERAFIM PEREIRA,'

console.log('YANNE MARINA LEITE OLIVEIRA, PRESIDENTA DA CÂMARA MUNICIPAL DE AURORA, TEM A HONRA DE CONVIDAR, EM NOME DO DIRETOR', nome,'TODA A EQUIPE GESTORA DA ESCOLA', escola, 'PARA A SESSÃO SOLENE DE ENTREGA DA MOÇÃO DE APLAUSOS À DIREÇÃO DA FACULDADE SANTA MARIA, EM HOMENAGEM E AGRADECIMENTO À INSTALAÇÃO DA INSTITUIÇÃO DE ENSINO, NO MUNICÍPIO DE AURORA-CE.')

console.log('YANNE MARINA LEITE OLIVEIRA, PRESIDENTA DA CÂMARA MUNICIPAL DE AURORA, TEM A HONRA DE CONVIDAR, EM NOME DA DIRETORA', nome,'TODA A EQUIPE GESTORA DA ESCOLA', escola, 'PARA A SESSÃO SOLENE DE ENTREGA DA MOÇÃO DE APLAUSOS À DIREÇÃO DA FACULDADE SANTA MARIA, EM HOMENAGEM E AGRADECIMENTO À INSTALAÇÃO DA INSTITUIÇÃO DE ENSINO, NO MUNICÍPIO DE AURORA-CE.')